# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=300)),
                ('id_no', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('batch', models.PositiveIntegerField()),
                ('height_inch', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('contact_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='teacher_name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select from below', 'select from below')], default='select from below', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assi_Professor'), ('Associate Professor', 'Asso_Professor'), ('Professor', 'Professor')], default='Lecturer', max_length=20),
        ),
    ]
